#!/usr/bin/env python3
"""
Render one WAV per tone_signal record.

Reads knowledge/records/tones.json and writes tests/fixtures/tones/<id>.wav
for each record whose technical_body describes a renderable tone (1 or 2
frequencies + a duration). Deterministic: fixed sample rate (8 kHz), fixed
amplitude (0.5), fixed integer sample count.

Two consumers:

  1. Regenerate fixtures locally when you need to hear or feed them into
     detector tests — the WAV files themselves are .gitignore'd because
     they're ~50-200 KB each, add up to a few MB, and are trivially
     reproducible from the records.

  2. Verify determinism: after rendering, this script writes / checks
     tests/fixtures/tones.sha256 (a plain text file, committed) so we
     catch cases where a records edit silently changes the audio a
     downstream test binds to.

Usage:
    python scripts/generate-tone-fixtures.py            # render + write checksums
    python scripts/generate-tone-fixtures.py --verify   # render + fail if checksums differ
    python scripts/generate-tone-fixtures.py --out DIR  # render to a different directory
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

from phr34cker5_mcp import tones  # noqa: E402

# Fixed rendering knobs — never touch these without regenerating checksums.
FIXTURE_AMPLITUDE = 0.5
FALLBACK_MS = 500  # for tones with no on_ms (e.g. MF control codes)

RECORDS_PATH = REPO_ROOT / "knowledge" / "records" / "tones.json"
DEFAULT_OUT = REPO_ROOT / "tests" / "fixtures" / "tones"
CHECKSUM_PATH = REPO_ROOT / "tests" / "fixtures" / "tones.sha256"


def render_record(rec: dict) -> bytes | None:
    """Render one tone_signal record to PCM bytes. Returns None if unrenderable."""
    tb = rec.get("technical_body") or {}
    freqs = tb.get("frequencies_hz") or []
    ms = tb.get("on_ms") or FALLBACK_MS

    if not isinstance(freqs, list) or len(freqs) == 0:
        return None
    if len(freqs) == 1:
        return tones.sine_bytes(float(freqs[0]), int(ms), FIXTURE_AMPLITUDE)
    if len(freqs) == 2:
        return tones.dual_tone_bytes(
            float(freqs[0]), float(freqs[1]), int(ms), FIXTURE_AMPLITUDE
        )
    # >2 frequencies: R2 MFC forward/backward sets describe a pool, not a
    # single burst. Skip; render R2 individual pairs via a separate tool if
    # needed.
    return None


def render_all(out_dir: Path) -> dict[str, str]:
    """Render every renderable record. Returns {filename: sha256} sorted by name."""
    out_dir.mkdir(parents=True, exist_ok=True)
    records = json.loads(RECORDS_PATH.read_text())

    checksums: dict[str, str] = {}
    for rec in records:
        pcm = render_record(rec)
        if pcm is None:
            continue
        rt = tones.write_wav(str(out_dir / f"{rec['id']}.wav"), pcm)
        wav_bytes = Path(rt.path).read_bytes()
        checksums[f"{rec['id']}.wav"] = hashlib.sha256(wav_bytes).hexdigest()

    return dict(sorted(checksums.items()))


def format_checksum_file(checksums: dict[str, str]) -> str:
    lines = [
        "# Auto-generated by scripts/generate-tone-fixtures.py",
        "# Rendered at 8000 Hz sample rate, amplitude 0.5.",
        "# One entry per renderable tone_signal record.",
        "",
    ]
    for name, digest in checksums.items():
        lines.append(f"{digest}  {name}")
    return "\n".join(lines) + "\n"


def parse_checksum_file(text: str) -> dict[str, str]:
    out: dict[str, str] = {}
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        digest, _, name = line.partition("  ")
        if digest and name:
            out[name] = digest
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT,
                    help=f"output directory (default: {_pretty(DEFAULT_OUT)})")
    ap.add_argument("--verify", action="store_true",
                    help="render and compare against the committed checksum file; fail if any differ")
    args = ap.parse_args()

    checksums = render_all(args.out)
    formatted = format_checksum_file(checksums)

    if args.verify:
        if not CHECKSUM_PATH.exists():
            print(f"ERROR: {CHECKSUM_PATH} does not exist. Run without --verify first.", file=sys.stderr)
            return 2
        expected = parse_checksum_file(CHECKSUM_PATH.read_text())
        differences = []
        for name, digest in checksums.items():
            if expected.get(name) != digest:
                differences.append((name, expected.get(name), digest))
        missing_from_generated = set(expected) - set(checksums)
        if differences or missing_from_generated:
            print("FAIL: fixture checksums do not match.", file=sys.stderr)
            for name, exp, got in differences:
                print(f"  {name}: expected {exp}, got {got}", file=sys.stderr)
            for name in sorted(missing_from_generated):
                print(f"  {name}: in checksum file but not generated", file=sys.stderr)
            return 1
        print(f"OK: {len(checksums)} fixtures match committed checksums.")
        return 0

    CHECKSUM_PATH.parent.mkdir(parents=True, exist_ok=True)
    CHECKSUM_PATH.write_text(formatted)
    print(f"Wrote {len(checksums)} fixtures to {_pretty(args.out)}/")
    print(f"Updated checksums at {_pretty(CHECKSUM_PATH)}")
    return 0


def _pretty(p: Path) -> str:
    """Format a path relative to the repo when possible, absolute otherwise."""
    try:
        return str(p.relative_to(REPO_ROOT))
    except ValueError:
        return str(p)


if __name__ == "__main__":
    sys.exit(main())
